[project]
name = "QMS-backend"
version = "0.0.0"
license = { file = "LICENSE" }
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["mypy", "ruff", "black"]

[tool.ruff]
select = ["E", "F", "N", "B", "A", "RET"]
line-length = 120
target-version = "py310"

[tool.black]
line-length = 120

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
exclude = ["build", ".venv"]
