MONITOR_VOLTMETER_CHANNEL = 1
DETECTOR_VOLTMETER_CHANNEL = 3
QUADRUPOLE_GENERATOR_CHANNEL = 2
DC_PLUS_HVPSU_CHANNEL = 1
DC_MINUS_HVPSU_CHANNEL = 2

MAX_SOURCE_VOLTAGE = 2e3
MAX_SOURCE_CURRENT = 1e-3

GENERATOR_AMPLITUDE_RF_TEST = 0.2

LAST_STATE_FILENAME = "last_state.json"
